const ADD_PRODUCT = "ADD_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const CALC_COST = "CALC_COST";

const MODIFY_QUANTITE_PRODUCT = "MODIFY_QUANTITE_PRODUCT";

export { CALC_COST, ADD_PRODUCT, DELETE_PRODUCT, MODIFY_QUANTITE_PRODUCT };
